/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWarehousesRouteImport } from './routes/_app.warehouses'
import { Route as AppUploadRouteImport } from './routes/_app.upload'
import { Route as AppRulesRouteImport } from './routes/_app.rules'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppContainersRouteImport } from './routes/_app.containers'
import { Route as AppBoardRouteImport } from './routes/_app.board'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppContainersRoute = AppContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/board': typeof AppBoardRoute
  '/containers': typeof AppContainersRoute
  '/customers': typeof AppCustomersRoute
  '/rules': typeof AppRulesRoute
  '/upload': typeof AppUploadRoute
  '/warehouses': typeof AppWarehousesRoute
}
export interface FileRoutesByTo {
  '/board': typeof AppBoardRoute
  '/containers': typeof AppContainersRoute
  '/customers': typeof AppCustomersRoute
  '/rules': typeof AppRulesRoute
  '/upload': typeof AppUploadRoute
  '/warehouses': typeof AppWarehousesRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/board': typeof AppBoardRoute
  '/_app/containers': typeof AppContainersRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/rules': typeof AppRulesRoute
  '/_app/upload': typeof AppUploadRoute
  '/_app/warehouses': typeof AppWarehousesRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/containers'
    | '/customers'
    | '/rules'
    | '/upload'
    | '/warehouses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/board'
    | '/containers'
    | '/customers'
    | '/rules'
    | '/upload'
    | '/warehouses'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/board'
    | '/_app/containers'
    | '/_app/customers'
    | '/_app/rules'
    | '/_app/upload'
    | '/_app/warehouses'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/warehouses': {
      id: '/_app/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upload': {
      id: '/_app/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules': {
      id: '/_app/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/containers': {
      id: '/_app/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AppContainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppContainersRoute: typeof AppContainersRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppRulesRoute: typeof AppRulesRoute
  AppUploadRoute: typeof AppUploadRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppContainersRoute: AppContainersRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppRulesRoute: AppRulesRoute,
  AppUploadRoute: AppUploadRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
